version: '3'

services:
  db:
    image: postgres:9.6-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - fhirnet
    volumes:
      - fhir-pgdata:/var/lib/postgresql/data
  fhir:
    build: .
    ports:
      - '8080:8080'
    environment:
      - POSTGRES_HOST=db 
      - SERVER_BASE_URL=http://localhost:8080
    networks:
      - fhirnet
    depends_on:
      - db

networks:
  fhirnet:
  
volumes:
  fhir-pgdata:
